### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by awafaa** [jangouts/jangouts#109]
Not 100% sure if the following errors are fatal or not in the running of Jangouts, but when I try and run <code>npm install && bower install</code> following the README I get the following error from npm, the bower stage goes fine with no errors or warnings:

[jangoutserror.txt](https://github.com/jangouts/jangouts/files/65714/jangoutserror.txt)

Just to confirm I am building on Tumbleweed.

**Comment by ancorgs** [comment]
I'm doing some cleanup of old issues.

As a side effect of GSoC, we have had some casual contributors. None of them have found problems setting up the development environment.

On the other hand, we have a "releases" section now, so you don't need to install npm or bower in order to use (or even configure) Jangouts.

Thus, closing this.
