### ISSUE TITLE
chat does not display unicode characters (or umlauts)

### ISSUE THREAD

**Issue by okurz** [jangouts/jangouts#149]
## observation

the chat window in jangouts does not display entered unicode characters, e.g. `…`.
## steps to reproduce

Try to type any non-ASCII character in a jangouts chat window, e.g. `üöäß…`
## problem

Character encoding not handled properly in jangouts.
## suggestion

It's 2016, use proper unicode everywhere.

**Comment by ancorgs** [comment]
From a mere observation of the symptoms, it is obvious (at least to developer's eyes) that the problem is not about encoding (Unicode is already used everywhere). If that would be the case, you would be seeing "funny" characters like our beloved �. Instead of that, the code of an HTML entity[1] is displayed, meaning the problem is about escaping (sanitizing) too much the user input. A problem that is still kind of common in 2016 if you combine several "third-party" components (something we have to do very often in Jangouts since it's faaaaar from being a full time job for us).

That been said. #166 should fix the problem by using a new ngEmbed configuration parameter introduced in October 2016. :wink:

[1] https://dev.w3.org/html5/html-author/charref
