### ISSUE TITLE
Polish the angular-2 branch

### ISSUE THREAD

**Issue by ancorgs** [jangouts/jangouts#156]
As you can see in the result page of the recent Google Summer of Code done by @magarcia[1], the port to Angular 2 is almost done, but some things were left behind. Specially these can be considered "regressions" when compared with the current master branch:
- Speak detected icon don't works properly.
- Show if one participant is set as "sticky".
- Add embeded links, images, emojis into chat.
- Reenable gridster (resizable areas) support for videoroom.
- Fix Pushtotalk key sequence record.
- Add hotkeys cheatsheet support.

We would like version 0.5.0 of jangouts to be based on that Angular 2 branch. Not only because of the new version of Angular, the branch also includes unit tests, better documentation, some small refactoring here and there...

But first we need to fix the six mentioned regressions.

[1] https://thingsofgeek.com/gsoc2016/

**Comment by imobachgs** [comment]
I plan to start working on this issue. The first step will be to update to the latest Angular version and make it work for a basic use case.

**Comment by Leo-14** [comment]
I am wondering if you guys are experienced this same issue while serving the angular-2 branch in  a chrome browser? the camera permission is reacting and the page is having an overlay pointing to reload the page as you can see in attached image. but every thing is working in firefoxe I am using chrome: Version 57.0.2987.110 (64-bit)

![chrome-behavior](https://cloud.githubusercontent.com/assets/26083138/25070663/8c0a75ec-229c-11e7-90ce-313c2ab9869d.png)

**Comment by code-master5** [comment]
@Leo-14 The screenshot shows that you're trying to run Jangouts simultaneously on both chrome and firefox. In my system, once the camera is accessed by firefox, I cannot use it on chrome (or vice versa). Your's might be the similar case. Please check this out. This might help.

**Comment by Leo-14** [comment]
@code-master5 Thanks for your reply,
I think that the problem is the browser version because i am still having the same thing even though I am using chrome only.
this is what other people are saying 
https://www.google.cm/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=chrome+57+not+allow+camera+to+be+shared

![screenshot_20170417_094900](https://cloud.githubusercontent.com/assets/26083138/25084589/5601e37c-2355-11e7-847b-4c6537f40f3a.png)

**Comment by code-master5** [comment]
The version I'm using is `57.0.2987.133 (64-bit)`. Jangouts (angular-branch) is working fine. I can't understand what's going wrong with your browser. 

But, after readings those red errors in your browser console, I guess the problem is not with your browser. Have you placed `config.json` inside `src` folder? Your browser doesn't seem to load this file. If you haven't, take hint from `src/config.json.sample` file. This might help!

**Comment by Leo-14** [comment]
okay thanks i will give a try.

**Comment by imobachgs** [comment]
We are dropping the Angular 2 port and going for React/Redux. See the [project](https://github.com/jangouts/jangouts/projects/1) for more details.
