### ISSUE TITLE
speak detection if muted

### ISSUE THREAD

**Issue by aschnell** [jangouts/jangouts#27]
When I'm muted (esp. if others muted me) and I start speaking Jangouts should detect that and inform me (e.g. with a bell).

Google Hangout does that.

**Comment by ancorgs** [comment]
With the new architecture in master (still in stabilization phase) this is easy to implement (I even have a prototype already).

**Comment by ancorgs** [comment]
This is 90% implemented in this commit (in a separate branch) https://github.com/jangouts/jangouts/commit/3bf2f0e2d1aa5c1cf99fa253094b577cf1f52d50

Any volunteer for the final tweaking? @ChrisBr @mdeniz

**Comment by ChrisBr** [comment]
Will have a look at this on the weekend!

**Comment by ChrisBr** [comment]
@ancorgs Do you want the suggested beel or sth different?

**Comment by ancorgs** [comment]
@ChrisBr I don't care much. Any sound will make it. There is already one included in  3bf2f0e2d1aa5c1cf99fa253094b577cf1f52d50 but feel to change it. The only really missing things on that commit are some fine-tunning of toastr settings and some way to avoid flooding the user with the same notification. But everything is temporary, feel free to change the message, the sound...

**Comment by ChrisBr** [comment]
@ancorgs Can you elaborate what you mean with your comment 
``
// TODO: introduce some timeout or any other mechanism to avoid
// repeating the notification over and over for the same speech
``

It works quite well for me ...

**Comment by ancorgs** [comment]
@ChrisbBr sure.while muted say something, then stay silent for just one second or even less, then speak again. Repeat several times and you will get a lot of bells and popups.now imagine they are keystrokes instead of words or that you muted because there is  somebody speaking next to you. Ring, ring, ring, ring...

Compare with hangouts in which you get just one notification unless you unmute and mute again or you stay silent for, let's say, one minute before speaking again.
