### ISSUE TITLE
FR: need push-to-talk mode

### ISSUE THREAD

**Issue by aspiers** [jangouts/jangouts#72]
Would be useful to be able to configure a keyboard shortcut for push-to-talk like with mumble.

**Comment by kbaikov** [comment]
+1 to that

**Comment by ancorgs** [comment]
@aspiers, @kbaikov I have deployed a preview of this feature (developed by @sandr3j) at https://jangouts.tk

Can you please give it a try and say if it fits your expectations.

**Comment by aspiers** [comment]
Awesome, thanks! We just tested this and it works great for some hotkeys (and I quite like the UI design), but not for others. For example, I tried using `Super_R + U` and for some weird reason it got incorrectly recognised as `\`.  Then I could press `\` to successfully push-to-talk, but of course that conflicts with using `\` for other purposes.

The other thing is that it will need persist the choice of hotkey between sessions - having to set it each time would be annoying.

**Comment by ancorgs** [comment]
I tried to reproduce, but for me `super` is always recorded as `meta`. @aspiers Which system/browser are you using?

**Comment by ancorgs** [comment]
To be precise, my `Super_L` is recorded as `meta`. I don't have a `Super_R` key.

**Comment by ancorgs** [comment]
Even after using xmodmap to remap my super key to `Super_R`, it is still being registered as `meta` by Jangouts.

**Comment by ancorgs** [comment]
Seems to be a general issue with the library we use (mousetrap). https://github.com/ccampbell/mousetrap/issues/81

So I would happily declare `super` to be unsupported.

Or maybe this other mousetrap alternative handles it better https://github.com/PolicyStat/combokeys... or maybe not.

**Comment by aspiers** [comment]
I'm using Chromium 49 on openSUSE 13.2.  A quick glance at https://github.com/ccampbell/mousetrap/issues/81 seems to suggest that they are using keycodes instead of keysyms to detect which key was pressed?!  If so, that's incredibly broken (because any keycode can be remapped to any keysym) and so you should avoid that library at all costs.  But maybe I'm missing something.

**Comment by aspiers** [comment]
And BTW I can't think of any good reason why some modifiers should be supported on Linux but not others.  They're supposed to be handled in the same way, as you can see via the modifier bitmap in `xev`.  Maybe it's because this is a cross-platform library and they're focusing on Windows/Mac :-/

**Comment by ancorgs** [comment]
Mousetrap is already used by AngularHotkeys, a component we are already using in other parts of Jangouts (which is not surprising, since Mousetrap is the most popular keystrokes library out there). Thus, it simply made sense to use it for the push-to-talk feature.

If we can find a (almost) drop-in replacement that doesn't interfere with Angular-Hotkeys, I'm fine with changing it now. But if it takes us more than a couple of minutes, I would rather consider the feature done for the time being (as soon as we implement persistence of the configuration) and would open a separate low-priority issue to replace Mousetrap.

**Comment by aspiers** [comment]
@ancorgs Sounds like a good approach to me.  Thanks!

**Comment by sandr3j** [comment]
@aspiers @ancorgs Thanks for your feedback. I checked today chromium and firefox on openSUSE 13.1 and could verify the problem. There are even some browser differences. I think we can at least exclude the problematic keys. I will investigate what kind of workaround might be the best. Of course there is no problem with adding the hotkey to persistent configuration. BTW why not just make the space key default and offer an option to change the key? I'm not sure if it is clear that the hotkey is never triggered while typing in the chatbox.

![screenshot - 04062016 - 03 58 38 pm](https://cloud.githubusercontent.com/assets/17593741/14335815/741e8e10-fc5e-11e5-9189-c8de1e073d20.png)

**Comment by ancorgs** [comment]
I would not activate push-to-talk by default. For me it's more an additional goodie than a core feature. Of course it has a usecase (that's why it was requested, after all), but I don't think it's an intuitive thing that most videoconferencing users would want/expect to be active.

In other news, the 1pixel increase in the header is back. :-)

**Comment by ancorgs** [comment]
@aspiers @kbaikov FYI, jangouts 0.4.4 (push-to-talk without key combinations) deployed in the internal SUSE's jangouts.

**Comment by aspiers** [comment]
Thanks!
